image: docker
services:
  - name: docker:dind
    variables:
      HEALTHCHECK_TCP_PORT: "2376"

stages:
  - test
  - deploy

variables:
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "/certs/client"
  COMPOSE_PROJECT_NAME: "test"
  DOCKER_DRIVER: overlay2

test:
  stage: test
  before_script:
#    - docker compose -f docker-compose.local.yaml up -d
  script:
#    - docker exec -t backend "pytest"
    - docker compose -f docker-compose.local.yaml run --rm backend pytest



#deploy:
#  stage: deploy
#  rules:
#      - if: $CI_COMMIT_BRANCH == "main"
#  before_script:
#    - apk update
#    - apk add openssh-client
#    - install -m 600 -D /dev/null ~/.ssh/id_rsa
#    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#    - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
#  script:
#    - ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && git checkout main && git pull && docker compose up -d --build && exit"
#  after_script:
#    - rm -rf ~/.ssh
