image: docker
services:
  - name: docker:dind
    variables:
      HEALTHCHECK_TCP_PORT: "2376"

stages:
  - test
  - deploy

variables:
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "/certs/client"
  COMPOSE_PROJECT_NAME: "test"
  DOCKER_DRIVER: overlay2

test:
  stage: test
  script:
    - docker compose -f docker-compose.local.yaml run --rm backend pytest



deploy:
  stage: deploy
  before_script:
    - apk add --no-cache ca-certificates openssh-client
    - apk update
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$known_key" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -i ~/.ssh/id_rsa ubuntu@$deploy_ip "cd $deploy_path && git pull origin master"
    - ssh -i ~/.ssh/id_rsa ubuntu@$deploy_ip "cd $deploy_path && echo \"${ENV_DATA}\" > .env"
    - ssh -i ~/.ssh/id_rsa ubuntu@$deploy_ip "cd $deploy_path && docker compose pull && docker compose up -d --build"
  only:
    - master
