"""add friends accept

Revision ID: 3bd5cedc587c
Revises: a44620ba10d5
Create Date: 2026-05-16 23:07:46.714791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd5cedc587c'
down_revision: Union[str, Sequence[str], None] = 'a44620ba10d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('accept', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'accept')
    # ### end Alembic commands ###
