"""drop created_by

Revision ID: 43616409ade4
Revises: 9127d8033a1e
Create Date: 2026-05-17 15:33:04.321571

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43616409ade4"
down_revision: Union[str, Sequence[str], None] = "9127d8033a1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("meetings_created_by_fkey"), "meetings", type_="foreignkey")
    op.drop_column("meetings", "created_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meetings",
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("meetings_created_by_fkey"),
        "meetings",
        "profiles",
        ["created_by"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
