"""fix friends bug

Revision ID: 8d249fc9f3c6
Revises: 6b1658877bab
Create Date: 2026-05-16 23:32:02.369843

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8d249fc9f3c6"
down_revision: Union[str, Sequence[str], None] = "6b1658877bab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
