"""accept may be null

Revision ID: 9127d8033a1e
Revises: 8d249fc9f3c6
Create Date: 2026-05-16 23:36:47.024783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9127d8033a1e'
down_revision: Union[str, Sequence[str], None] = '8d249fc9f3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'accept',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friends', 'accept',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
