"""add refresh token

Revision ID: a5b51cfde23f
Revises: f6a0e0de222a
Create Date: 2026-05-16 14:05:23.185931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b51cfde23f'
down_revision: Union[str, Sequence[str], None] = 'f6a0e0de222a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_members_meeting_id'), table_name='meeting_members')
    op.drop_index(op.f('ix_meeting_members_profile_id'), table_name='meeting_members')
    op.drop_index(op.f('ix_meetings_created_by'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_starts_at'), table_name='meetings')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')

    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))

    op.execute("UPDATE users SET refresh_token = ' ' WHERE refresh_token IS NULL")

    op.alter_column('users', 'refresh_token', nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'refresh_token')
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_meetings_starts_at'), 'meetings', ['starts_at'], unique=False)
    op.create_index(op.f('ix_meetings_created_by'), 'meetings', ['created_by'], unique=False)
    op.create_index(op.f('ix_meeting_members_profile_id'), 'meeting_members', ['profile_id'], unique=False)
    op.create_index(op.f('ix_meeting_members_meeting_id'), 'meeting_members', ['meeting_id'], unique=False)
    # ### end Alembic commands ###
