"""bug fix

Revision ID: f6a0e0de222a
Revises: ebdb2d8ad259
Create Date: 2026-05-16 00:16:47.772382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a0e0de222a'
down_revision: Union[str, Sequence[str], None] = 'ebdb2d8ad259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'meeting_members', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meeting_members', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meetings', 'profiles', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_constraint(None, 'meeting_members', type_='foreignkey')
    op.drop_constraint(None, 'meeting_members', type_='foreignkey')
    # ### end Alembic commands ###
